# Generated by Django 3.2.25 on 2024-10-02 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=75)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('S', 'Supervisor'), ('D', 'Driver'), ('R', 'Rider')], default='S', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('assigned', 'Assigned')], default='available', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('van_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ADA', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(limit_choices_to={'user_type': 'D'}, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('num_passengers', models.IntegerField(default=1)),
                ('ADA_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'D'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_driver', to='api.user')),
                ('rider', models.ForeignKey(limit_choices_to={'user_type': 'R'}, on_delete=django.db.models.deletion.CASCADE, related_name='ride_rider', to='api.user')),
                ('van', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.van')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('safety', 'Safety Issue'), ('service', 'Service Issue'), ('delay', 'Delay'), ('vehicle', 'Vehicle Condition'), ('other', 'Other')], max_length=20)),
                ('context', models.TextField()),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rider', models.ForeignKey(limit_choices_to={'user_type': 'R'}, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('driver', models.ForeignKey(limit_choices_to={'user_type': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='messages_as_driver', to='api.user')),
                ('rider', models.ForeignKey(limit_choices_to={'user_type': 'R'}, on_delete=django.db.models.deletion.CASCADE, related_name='messages_as_rider', to='api.user')),
            ],
        ),
    ]
