# Generated by Django 5.1.1 on 2024-09-26 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('supervisor', 'Supervisor')], max_length=20)),
                ('panther_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('supervisor', 'Supervisor')], max_length=20)),
                ('panther_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('supervisor', 'Supervisor')], max_length=20)),
                ('supervisor_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rider')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rider')),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('num_passengers', models.IntegerField(default=1)),
                ('ADA_required', models.BooleanField(default=False)),
                ('ride_status', models.CharField(default='Pending', max_length=50)),
                ('pickup_time', models.DateTimeField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rider')),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('van_number', models.AutoField(primary_key=True, serialize=False)),
                ('ADA', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('num_passengers', models.IntegerField(default=1)),
                ('is_accessible', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rider')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.van')),
            ],
        ),
    ]
