# Generated by Django 5.1.2 on 2024-10-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('S', 'Supervisor'), ('D', 'Driver'), ('R', 'Rider'), ('A', 'Admin')], default='R', max_length=1),
        ),
    ]
