# Generated by Django 5.0.6 on 2024-10-25 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ride'),
        ),
    ]
