# Generated by Django 5.1.2 on 2024-10-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_ride_ride_id_ride_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='van_number',
            field=models.CharField(default=12345, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='van',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
