# Generated by Django 5.0.6 on 2024-11-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_van_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driverName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
