# Generated by Django 5.0.6 on 2024-11-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ride_drivername'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
