# Generated by Django 5.0.6 on 2024-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ride_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='riderName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
